export interface Country {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "AF", dialCode: "+93", flag: "🇦🇫" },
  { name: "Afrique du Sud", code: "ZA", dialCode: "+27", flag: "🇿🇦" },
  { name: "Albanie", code: "AL", dialCode: "+355", flag: "🇦🇱" },
  { name: "Algérie", code: "DZ", dialCode: "+213", flag: "🇩🇿" },
  { name: "Allemagne", code: "DE", dialCode: "+49", flag: "🇩🇪" },
  { name: "Andorre", code: "AD", dialCode: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴" },
  { name: "Arabie Saoudite", code: "SA", dialCode: "+966", flag: "🇸🇦" },
  { name: "Argentine", code: "AR", dialCode: "+54", flag: "🇦🇷" },
  { name: "Arménie", code: "AM", dialCode: "+374", flag: "🇦🇲" },
  { name: "Australie", code: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "Autriche", code: "AT", dialCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaïdjan", code: "AZ", dialCode: "+994", flag: "🇦🇿" },
  { name: "Bahreïn", code: "BH", dialCode: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", dialCode: "+880", flag: "🇧🇩" },
  { name: "Belgique", code: "BE", dialCode: "+32", flag: "🇧🇪" },
  { name: "Bénin", code: "BJ", dialCode: "+229", flag: "🇧🇯" },
  { name: "Bolivie", code: "BO", dialCode: "+591", flag: "🇧🇴" },
  { name: "Bosnie-Herzégovine", code: "BA", dialCode: "+387", flag: "🇧🇦" },
  { name: "Brésil", code: "BR", dialCode: "+55", flag: "🇧🇷" },
  { name: "Bulgarie", code: "BG", dialCode: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", dialCode: "+226", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", dialCode: "+257", flag: "🇧🇮" },
  { name: "Cambodge", code: "KH", dialCode: "+855", flag: "🇰🇭" },
  { name: "Cameroun", code: "CM", dialCode: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "Chili", code: "CL", dialCode: "+56", flag: "🇨🇱" },
  { name: "Chine", code: "CN", dialCode: "+86", flag: "🇨🇳" },
  { name: "Chypre", code: "CY", dialCode: "+357", flag: "🇨🇾" },
  { name: "Colombie", code: "CO", dialCode: "+57", flag: "🇨🇴" },
  { name: "Comores", code: "KM", dialCode: "+269", flag: "🇰🇲" },
  { name: "Congo (RDC)", code: "CD", dialCode: "+243", flag: "🇨🇩" },
  { name: "Congo (République)", code: "CG", dialCode: "+242", flag: "🇨🇬" },
  { name: "Corée du Sud", code: "KR", dialCode: "+82", flag: "🇰🇷" },
  { name: "Costa Rica", code: "CR", dialCode: "+506", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", code: "CI", dialCode: "+225", flag: "🇨🇮" },
  { name: "Croatie", code: "HR", dialCode: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", dialCode: "+53", flag: "🇨🇺" },
  { name: "Danemark", code: "DK", dialCode: "+45", flag: "🇩🇰" },
  { name: "Djibouti", code: "DJ", dialCode: "+253", flag: "🇩🇯" },
  { name: "Égypte", code: "EG", dialCode: "+20", flag: "🇪🇬" },
  { name: "Émirats arabes unis", code: "AE", dialCode: "+971", flag: "🇦🇪" },
  { name: "Équateur", code: "EC", dialCode: "+593", flag: "🇪🇨" },
  { name: "Espagne", code: "ES", dialCode: "+34", flag: "🇪🇸" },
  { name: "Estonie", code: "EE", dialCode: "+372", flag: "🇪🇪" },
  { name: "États-Unis", code: "US", dialCode: "+1", flag: "🇺🇸" },
  { name: "Éthiopie", code: "ET", dialCode: "+251", flag: "🇪🇹" },
  { name: "Finlande", code: "FI", dialCode: "+358", flag: "🇫🇮" },
  { name: "France", code: "FR", dialCode: "+33", flag: "🇫🇷" },
  { name: "Gabon", code: "GA", dialCode: "+241", flag: "🇬🇦" },
  { name: "Gambie", code: "GM", dialCode: "+220", flag: "🇬🇲" },
  { name: "Géorgie", code: "GE", dialCode: "+995", flag: "🇬🇪" },
  { name: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭" },
  { name: "Grèce", code: "GR", dialCode: "+30", flag: "🇬🇷" },
  { name: "Guatemala", code: "GT", dialCode: "+502", flag: "🇬🇹" },
  { name: "Guinée", code: "GN", dialCode: "+224", flag: "🇬🇳" },
  { name: "Haïti", code: "HT", dialCode: "+509", flag: "🇭🇹" },
  { name: "Honduras", code: "HN", dialCode: "+504", flag: "🇭🇳" },
  { name: "Hongrie", code: "HU", dialCode: "+36", flag: "🇭🇺" },
  { name: "Inde", code: "IN", dialCode: "+91", flag: "🇮🇳" },
  { name: "Indonésie", code: "ID", dialCode: "+62", flag: "🇮🇩" },
  { name: "Irak", code: "IQ", dialCode: "+964", flag: "🇮🇶" },
  { name: "Iran", code: "IR", dialCode: "+98", flag: "🇮🇷" },
  { name: "Irlande", code: "IE", dialCode: "+353", flag: "🇮🇪" },
  { name: "Islande", code: "IS", dialCode: "+354", flag: "🇮🇸" },
  { name: "Israël", code: "IL", dialCode: "+972", flag: "🇮🇱" },
  { name: "Italie", code: "IT", dialCode: "+39", flag: "🇮🇹" },
  { name: "Jamaïque", code: "JM", dialCode: "+1876", flag: "🇯🇲" },
  { name: "Japon", code: "JP", dialCode: "+81", flag: "🇯🇵" },
  { name: "Jordanie", code: "JO", dialCode: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪" },
  { name: "Koweït", code: "KW", dialCode: "+965", flag: "🇰🇼" },
  { name: "Lettonie", code: "LV", dialCode: "+371", flag: "🇱🇻" },
  { name: "Liban", code: "LB", dialCode: "+961", flag: "🇱🇧" },
  { name: "Libye", code: "LY", dialCode: "+218", flag: "🇱🇾" },
  { name: "Lituanie", code: "LT", dialCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", dialCode: "+352", flag: "🇱🇺" },
  { name: "Madagascar", code: "MG", dialCode: "+261", flag: "🇲🇬" },
  { name: "Malaisie", code: "MY", dialCode: "+60", flag: "🇲🇾" },
  { name: "Mali", code: "ML", dialCode: "+223", flag: "🇲🇱" },
  { name: "Malte", code: "MT", dialCode: "+356", flag: "🇲🇹" },
  { name: "Maroc", code: "MA", dialCode: "+212", flag: "🇲🇦" },
  { name: "Maurice", code: "MU", dialCode: "+230", flag: "🇲🇺" },
  { name: "Mauritanie", code: "MR", dialCode: "+222", flag: "🇲🇷" },
  { name: "Mexique", code: "MX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Moldavie", code: "MD", dialCode: "+373", flag: "🇲🇩" },
  { name: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨" },
  { name: "Mongolie", code: "MN", dialCode: "+976", flag: "🇲🇳" },
  { name: "Monténégro", code: "ME", dialCode: "+382", flag: "🇲🇪" },
  { name: "Mozambique", code: "MZ", dialCode: "+258", flag: "🇲🇿" },
  { name: "Myanmar", code: "MM", dialCode: "+95", flag: "🇲🇲" },
  { name: "Népal", code: "NP", dialCode: "+977", flag: "🇳🇵" },
  { name: "Nicaragua", code: "NI", dialCode: "+505", flag: "🇳🇮" },
  { name: "Niger", code: "NE", dialCode: "+227", flag: "🇳🇪" },
  { name: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬" },
  { name: "Norvège", code: "NO", dialCode: "+47", flag: "🇳🇴" },
  { name: "Nouvelle-Zélande", code: "NZ", dialCode: "+64", flag: "🇳🇿" },
  { name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲" },
  { name: "Ouganda", code: "UG", dialCode: "+256", flag: "🇺🇬" },
  { name: "Ouzbékistan", code: "UZ", dialCode: "+998", flag: "🇺🇿" },
  { name: "Pakistan", code: "PK", dialCode: "+92", flag: "🇵🇰" },
  { name: "Palestine", code: "PS", dialCode: "+970", flag: "🇵🇸" },
  { name: "Panama", code: "PA", dialCode: "+507", flag: "🇵🇦" },
  { name: "Paraguay", code: "PY", dialCode: "+595", flag: "🇵🇾" },
  { name: "Pays-Bas", code: "NL", dialCode: "+31", flag: "🇳🇱" },
  { name: "Pérou", code: "PE", dialCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", dialCode: "+63", flag: "🇵🇭" },
  { name: "Pologne", code: "PL", dialCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦" },
  { name: "République dominicaine", code: "DO", dialCode: "+1809", flag: "🇩🇴" },
  { name: "République tchèque", code: "CZ", dialCode: "+420", flag: "🇨🇿" },
  { name: "Roumanie", code: "RO", dialCode: "+40", flag: "🇷🇴" },
  { name: "Royaume-Uni", code: "GB", dialCode: "+44", flag: "🇬🇧" },
  { name: "Russie", code: "RU", dialCode: "+7", flag: "🇷🇺" },
  { name: "Rwanda", code: "RW", dialCode: "+250", flag: "🇷🇼" },
  { name: "Salvador", code: "SV", dialCode: "+503", flag: "🇸🇻" },
  { name: "Sénégal", code: "SN", dialCode: "+221", flag: "🇸🇳" },
  { name: "Serbie", code: "RS", dialCode: "+381", flag: "🇷🇸" },
  { name: "Singapour", code: "SG", dialCode: "+65", flag: "🇸🇬" },
  { name: "Slovaquie", code: "SK", dialCode: "+421", flag: "🇸🇰" },
  { name: "Slovénie", code: "SI", dialCode: "+386", flag: "🇸🇮" },
  { name: "Somalie", code: "SO", dialCode: "+252", flag: "🇸🇴" },
  { name: "Soudan", code: "SD", dialCode: "+249", flag: "🇸🇩" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", flag: "🇱🇰" },
  { name: "Suède", code: "SE", dialCode: "+46", flag: "🇸🇪" },
  { name: "Suisse", code: "CH", dialCode: "+41", flag: "🇨🇭" },
  { name: "Syrie", code: "SY", dialCode: "+963", flag: "🇸🇾" },
  { name: "Taïwan", code: "TW", dialCode: "+886", flag: "🇹🇼" },
  { name: "Tanzanie", code: "TZ", dialCode: "+255", flag: "🇹🇿" },
  { name: "Tchad", code: "TD", dialCode: "+235", flag: "🇹🇩" },
  { name: "Thaïlande", code: "TH", dialCode: "+66", flag: "🇹🇭" },
  { name: "Togo", code: "TG", dialCode: "+228", flag: "🇹🇬" },
  { name: "Tunisie", code: "TN", dialCode: "+216", flag: "🇹🇳" },
  { name: "Turquie", code: "TR", dialCode: "+90", flag: "🇹🇷" },
  { name: "Ukraine", code: "UA", dialCode: "+380", flag: "🇺🇦" },
  { name: "Uruguay", code: "UY", dialCode: "+598", flag: "🇺🇾" },
  { name: "Venezuela", code: "VE", dialCode: "+58", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", dialCode: "+84", flag: "🇻🇳" },
  { name: "Yémen", code: "YE", dialCode: "+967", flag: "🇾🇪" },
  { name: "Zambie", code: "ZM", dialCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: "🇿🇼" },
];

export function getCountryByCode(code: string): Country | undefined {
  return countries.find(c => c.code === code);
}

export function searchCountries(query: string): Country[] {
  const q = query.toLowerCase();
  return countries.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.code.toLowerCase().includes(q) ||
    c.dialCode.includes(q)
  );
}
